opintotuki = float(input("Enter the amount of the study benefits: "))
uusi = (opintotuki * 1.0117)
print("If the index raise is 1.17 percent, the study benefit,")
print("after a raise, would be",uusi,"euros")
kuusi = (uusi * 1.0117)
print("and if there was another index raise, the study")
print("benefits would be as much as",kuusi,"euros")
